// Catálogo curado de íconos Lucide para misiones — espejo del render de la
// app (frontend/src/components/gamification/missionIcons.ts). Cerrado a
// propósito: todo lo que este picker ofrece, la app lo dibuja garantizado.

import type { LucideIcon } from 'lucide-react';
import {
  Award,
  Bell,
  BookOpen,
  Brain,
  Calendar,
  CalendarCheck,
  CheckCheck,
  Clock,
  Compass,
  Crown,
  Dumbbell,
  Feather,
  Flag,
  Flame,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Lightbulb,
  Map,
  Medal,
  Mountain,
  Pencil,
  Puzzle,
  Rocket,
  Shield,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Swords,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Zap,
} from 'lucide-react';

export const MISSION_ICONS: Record<string, LucideIcon> = {
  award: Award,
  bell: Bell,
  'book-open': BookOpen,
  brain: Brain,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'check-check': CheckCheck,
  clock: Clock,
  compass: Compass,
  crown: Crown,
  dumbbell: Dumbbell,
  feather: Feather,
  flag: Flag,
  flame: Flame,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  heart: Heart,
  lightbulb: Lightbulb,
  map: Map,
  medal: Medal,
  mountain: Mountain,
  pencil: Pencil,
  puzzle: Puzzle,
  rocket: Rocket,
  shield: Shield,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  swords: Swords,
  target: Target,
  timer: Timer,
  'trending-up': TrendingUp,
  trophy: Trophy,
  users: Users,
  zap: Zap,
};

export const MISSION_ICON_NAMES = Object.keys(MISSION_ICONS);
